# .github/workflows/cd.yml
name: CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t mymodel:latest .
      
      - name: Push to DockerHub
        run: docker push mydockerhubusername/mymodel:latest
